### PR TITLE
Adds CLI tools for recursive-copy and recursive-delete.

### PR DESCRIPTION
**Pull request by MicahZoltu**
These CLI tools offer a nice no-frills alternative to the bloated 73-package copyfiles and 11 package rimraf.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Fixes #1

**Comment by MicahZoltu** [comment]
If you aren't interested in merging this PR please let me know so I can publish something like `recursive-fs-cli` to NPM myself.  I would prefer to just have your library on NPM with the CLI tooling included, but I'm not opposed to publishing myself if that doesn't interest you.

**Comment by simov** [comment]
Give me some time to review it. I'll take a look at it later today.

**Comment by simov** [comment]
I merged your commit, but GitHub is acting weird because of the force-pushed commits. Must be a newer _feature_ or something. Anyway, I made a few small changes and published it in v1.1.0, let me know if you have any issues.

**Pull request closed without merging**
